[package]
name = "crates-rustdoc-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
crates_io_api = "0.8.0"
duct = "0.13.5"
