[build]
target-dir = "/home/predrag/.scratch/.rustc-target/crates-rustdoc-gen/target"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang-12"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
